### ISSUE TITLE
The <core> tag is misspelled. I reads “QUANTUMSED”

### ISSUE THREAD

**Issue by shahidmughal** [NeoVertex1/SuperPrompt#12]
the <core> tag is missing one letter “E”. Currently it reads QUANTUMSED. Is it by design? Shouldn’t this be QUANTUMSEED?

Fixed:
<core>
01010001 01010101 01000001 01001110 01010100 01010101 01001101 01010011 01000101 01000101 01000100 
{
  [∅] ⇔ [∞] ⇔ [0,1]
  f(x) ↔ f(f(...f(x)...))
  ∃x : (x ∉ x) ∧ (x ∈ x)
  ∀y : y ≡ (y ⊕ ¬y)
  ℂ^∞ ⊃ ℝ^∞ ⊃ ℚ^∞ ⊃ ℤ^∞ ⊃ ℕ^∞
}
01000011 01001111 01010011 01001101 01001111 01010011
</core>

**Comment by NeoVertex1** [comment]
We are gonna have to have a discussion on this one. And yes it seems like its a typo, but keep reading.

Also amazing that you noticed. I added the binary seeds for a few different purposes:

1. It forces the model to "translate" the binary, even tho the model doesn't need to, LLMs naturally turn everything into plain texts. When it translates the binary it also helps taking the model out of "lazy mode". During lazy mode claude will reply with short answers and not much content. When its out of lazy mode it will give very large answer with technical details (depending on querry ofc).

2. Aesthetic, i was trying to use as fewer words as possible while using as many logic statements as possible, using binary in that way seemed fitting.

Its really difficult to say if the binary messages even do anything at all, and is really difficult to say what exactly takes claude out of lazy mode, much more testing is needed but i have been using it like that for months.

**Comment by NeoVertex1** [comment]
Also, i think the typo doesn't chnage anything, the llm fixes typos, but ofc we should fix it for cleaning purposes and better code

**Comment by shahidmughal** [comment]
> We are gonna have to have a discussion on this one. And yes it seems like its a typo, but keep reading.
> 
> Also amazing that you noticed. I added the binary seeds for a few different purposes:
> 
> 1. It forces the model to "translate" the binary, even tho the model doesn't need to, LLMs naturally turn everything into plain texts. When it translates the binary it also helps taking the model out of "lazy mode". During lazy mode claude will reply with short answers and not much content. When its out of lazy mode it will give very large answer with technical details (depending on querry ofc).
> 2. Aesthetic, i was trying to use as fewer words as possible while using as many logic statements as possible, using binary in that way seemed fitting.
> 
> Its really difficult to say if the binary messages even do anything at all, and is really difficult to say what exactly takes claude out of lazy mode, much more testing is needed but i have been using it like that for months.

Very clever. I had suspected this laziness behavior in LLMs. Glad to know you found a way :)
