### ISSUE TITLE
I would suggest not using triple double quotes """ 

### ISSUE THREAD

**Issue by mobilestack** [NeoVertex1/SuperPrompt#32]
As this is often used in python as well, to quote a long long text. And we do need to adapt to it, either I have to change it to something like ===, or escape it with \

That is my recommendation.

But anyway, we can use \"\"\" to escape it.

**Comment by NeoVertex1** [comment]
Can you remind me where it is being used?

**Comment by mobilestack** [comment]
> Can you remind me where it is being used?

Let's say, if I use a piece of python code to use your super prompt. I would do something like this:

```
super_prompt = """
SUPER_PROMPT
""" 

API_CALL(system_prompt=super_prompt, user_prompt)
```

The problem is that inside the SUPER_PROMPT, there are also """, which makes that python syntax not working.

**Comment by NeoVertex1** [comment]
> > Can you remind me where it is being used?
> 
> 
> 
> Let's say, if I use a piece of python code to use your super prompt. I would do something like this:
> 
> 
> 
> ```
> 
> super_prompt = """
> 
> SUPER_PROMPT
> 
> """ 
> 
> 
> 
> API_CALL(system_prompt=super_prompt, user_prompt)
> 
> ```
> 
> 
> 
> The problem is that inside the SUPER_PROMPT, there are also """, which makes that python syntax not working.
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 

The problem is that python code does not work well in prompts tho, but let me know if you get any good results
