### ISSUE TITLE
new tm_prompt ignores most tags if not told

### ISSUE THREAD

**Issue by NeoVertex1** [NeoVertex1/SuperPrompt#41]
the new tm_prompt is amazing but something is wrong maybe in the order that things are being done that makes Claude ignore most of the tags unless you specifically say so, what should we do? most importantly its not using the prompt metadata correctly, thats a major flaw. also congrats on this prompt it really makes claude think deep.

<img width="748" alt="Screenshot 2024-10-10 at 15 10 37" src="https://github.com/user-attachments/assets/f8a8687a-58e9-4fe9-95f8-ec96163b4388">
<img width="775" alt="Screenshot 2024-10-10 at 15 10 44" src="https://github.com/user-attachments/assets/6c6e6a0f-1859-4d07-a6fa-cd6bd367bc40">

**Comment by phughesmcr** [comment]
I've made a couple of small changes to the prompt to try and fix this - starting the chat with "Hi Claude, initialize your <core> please" seems to be a good way of "preheating" the conversation

**Comment by NeoVertex1** [comment]
Great, let us optimize, this version is good im gonna work on it
